<a href="https://colab.research.google.com/github/DebadityaShome/Deep-learning-practice/blob/main/PyTorch/tutorials/linearNN_on_dummyData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [27]:
# Input (temp, rainfall, humidity)
inputs = 100. * np.random.random((45, 3)).astype('float32')
targets = 100. * np.random.random((45, 2)).astype('float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

## **Dataset and DataLoader**

In [28]:
from torch.utils.data import TensorDataset

In [29]:
# Define dataset
train_ds = TensorDataset(inputs, targets) # Tuples of X, y tensor pairs
train_ds[0:3]

(tensor([[15.4582, 11.0468, 39.8135],
         [35.0071, 57.6199, 34.6630],
         [25.3790, 54.7686, 55.4064]]), tensor([[78.6066, 79.6434],
         [34.0873, 19.7547],
         [13.1934, 29.3280]]))

In [30]:
from torch.utils.data import DataLoader

In [31]:
# Define dataloader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [32]:
# Print and check one training data batch
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[58.1864, 75.9520, 70.5568],
        [92.1290, 20.9319, 61.5432],
        [77.3177,  8.8310,  8.6547],
        [75.9336, 21.9865, 93.6252],
        [32.9868, 87.9542,  2.1557]])
tensor([[85.4138, 77.6122],
        [43.0344, 74.1679],
        [14.6543, 95.3472],
        [13.8537, 75.7735],
        [ 4.2567, 37.2163]])


In [33]:
# Define a simple single-layer linear neural network
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3431, -0.4446, -0.3157],
        [ 0.2186,  0.2635, -0.4932]], requires_grad=True)
Parameter containing:
tensor([0.4089, 0.0768], requires_grad=True)


In [34]:
# Printing all model parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3431, -0.4446, -0.3157],
         [ 0.2186,  0.2635, -0.4932]], requires_grad=True),
 Parameter containing:
 tensor([0.4089, 0.0768], requires_grad=True)]

In [35]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-11.7696, -13.2696],
        [-24.1444,   5.8176],
        [-32.7296,  -7.2698],
        [-35.6754,  -1.9877],
        [ -4.8271, -22.3572],
        [-47.7180,  10.1791],
        [-39.8809, -36.5801],
        [  4.8507,  30.7683],
        [-33.6778, -41.2918],
        [-47.6115, -34.0746],
        [-40.2085,  18.1395],
        [-12.4694,   4.2809],
        [  6.8519,  -4.1441],
        [ 20.2790,  15.0385],
        [-11.8128, -16.7482],
        [ -5.6935,  -8.9072],
        [ -6.5800,   0.3012],
        [-17.9162, -11.6682],
        [-14.9660,  25.3172],
        [-48.1130, -30.7909],
        [  3.2816,  -4.6206],
        [ -9.2211,   5.0083],
        [-34.8900,  25.6604],
        [-19.6164, -39.2904],
        [-54.5251, -20.4827],
        [-55.7987,  -5.6746],
        [-26.9343,  20.5078],
        [-25.6957, -14.2242],
        [-28.0619,  29.4033],
        [-47.6481,  -1.2712],
        [-35.3495,  -6.3087],
        [-40.5756,   8.4835],
        [ -6.0532, -12.6079],
        [-

In [37]:
# Define loss function
loss_fn = F.mse_loss

# Calculate loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(5747.9526, grad_fn=<MseLossBackward>)


In [38]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [39]:
# Custom training loop
def fit(num_epochs, model, loss_fn, opt, train_dl):

    for epoch in range(num_epochs):
        
        for xb, yb in train_dl:

            pred = model(xb)

            loss = loss_fn(pred, yb)

            loss.backward()

            opt.step()

            opt.zero_grad()
    
    if (epoch+1) % 10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [51]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [100/100], Loss: 476.9442
