<a href="https://colab.research.google.com/github/DebadityaShome/Deep-learning-practice/blob/main/PyTorch/PyTorch_basics_cheatsheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

1.8.1+cu101


In [2]:
## Initializing tensors
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device="cpu")
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
## Common intialization methods
x = torch.empty(size = (3, 3))
print(x)
x = torch.zeros(())
print(x)
x = torch.rand((3, 3))
print(x)
x = torch.ones((3, 3))
print(x)
x = torch.eye(5, 5)
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)
x = torch.empty(size=(1, 5)).uniform_(0, 1)
print(x)
x = torch.diag(torch.ones(3))
print(x)

tensor([[-5.2745e+10,  3.0631e-41, -5.7924e+10],
        [ 3.0631e-41, -7.1837e+10,  3.0631e-41],
        [-2.4319e+10,  3.0631e-41, -7.1813e+10]])
tensor(0.)
tensor([[0.3706, 0.5319, 0.4394],
        [0.1723, 0.4002, 0.2370],
        [0.9204, 0.8165, 0.3673]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-1.2605,  0.4480,  1.5648,  0.7767,  0.0423]])
tensor([[0.6508, 0.0416, 0.7558, 0.2743, 0.0780]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [11]:
# Array to Tensor conversion
import numpy as np
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)

# Vice-versa
np_array_back = tensor.numpy()

## **Math and comparison operations**

In [12]:
# Addition
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
z1 = torch.empty(3)
torch.add(x, y, out=z1) # First way
print(z1)
z2 = torch.add(x, y) # Second way (Preferred)
print(z2)

tensor([10., 10., 10.])
tensor([10, 10, 10])


In [13]:
# Subtraction
z = x - y

In [14]:
# Division
z = torch.true_divide(x, y) 

In [15]:
# inplace operations
# All operations with an underscore (_) added at the end are inplace operations in torch
t = torch.zeros(3)
t.add_(x)

tensor([1., 2., 3.])

In [16]:
# Exponentiation
z = x.pow(2)
z = x ** 2

# Simple comparisons
z = x > 0
z = x < 0

In [17]:
# Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 1st way
x3 = x1.mm(x2) # 2nd way

In [21]:
# Matrix exponentiation
matrix = torch.rand(5, 5)
print(matrix)
print(matrix.matrix_power(3))

tensor([[0.0645, 0.3473, 0.5203, 0.4274, 0.7344],
        [0.6866, 0.3455, 0.9288, 0.2176, 0.4864],
        [0.6037, 0.0828, 0.5129, 0.3814, 0.6030],
        [0.9940, 0.2875, 0.7389, 0.0828, 0.3184],
        [0.2386, 0.0347, 0.4733, 0.2628, 0.0063]])
tensor([[1.7673, 0.7994, 2.2810, 1.2779, 1.9607],
        [2.5367, 1.0087, 3.1410, 1.6182, 2.3295],
        [1.9565, 0.7879, 2.4152, 1.2482, 1.8349],
        [2.4325, 0.8952, 2.9293, 1.4365, 2.0103],
        [0.9875, 0.4356, 1.3038, 0.6977, 0.9966]])


In [22]:
# Element wise multiplication
z = x * y
print(z)

tensor([ 9, 16, 21])


In [23]:
# Dot product
Z = torch.dot(x, y)
print(Z)

tensor(46)


In [24]:
# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

In [28]:
# Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2  # x2 would be broadcasted (automatically expanded) from (1 x 5) to (5 x 5)
z = x1 ** x2 # x2 would be broadcasted (automatically expanded) from (1 x 5) to (5 x 5)

In [31]:
# Other useful tensor operations
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x) # absolute value
z = torch.argmax(x, dim=0)  # Returns index of maximum
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y) # Boolean indicating if two tensors are equal or not
sorted_y, indices = torch.sort(y, dim=0, descending=False)

In [32]:
z = torch.clamp(x, min=0) # clamps the value to be between min and max

In [33]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
z = torch.any(x)
print(z)

tensor(True)


## **Tensor indexing**

In [42]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [45]:
# Get all features of the first  batch
print(x[0])
print(x[0, :]) ## same

tensor([0.0612, 0.7926, 0.6711, 0.9714, 0.7172, 0.4337, 0.9874, 0.0784, 0.1499,
        0.1561, 0.3474, 0.1976, 0.5718, 0.0525, 0.7681, 0.6785, 0.0447, 0.8151,
        0.3494, 0.8551, 0.5453, 0.7473, 0.9732, 0.3800, 0.0061])
tensor([0.0612, 0.7926, 0.6711, 0.9714, 0.7172, 0.4337, 0.9874, 0.0784, 0.1499,
        0.1561, 0.3474, 0.1976, 0.5718, 0.0525, 0.7681, 0.6785, 0.0447, 0.8151,
        0.3494, 0.8551, 0.5453, 0.7473, 0.9732, 0.3800, 0.0061])


In [46]:
# Get first feature from all the batches
print(x[:, 0])

tensor([0.0612, 0.0467, 0.8516, 0.2784, 0.6485, 0.4667, 0.4757, 0.9826, 0.2730,
        0.8568])


In [47]:
# Get third batch and first ten features
print(x[2, :10])

tensor([0.8516, 0.7736, 0.9119, 0.5165, 0.8589, 0.9460, 0.5859, 0.0914, 0.9560,
        0.3036])


In [50]:
# Fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])  # Picks 3rd, 6th and 8th examples from the batch

tensor([2, 5, 8])


In [54]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(rows, cols, x)
print(x[rows, cols])  # Picks out elements at indices (1, 4) and (0, 0)

tensor([1, 0]) tensor([4, 0]) tensor([[0.7487, 0.0949, 0.0113, 0.4540, 0.4770],
        [0.2928, 0.5132, 0.6460, 0.0765, 0.2650],
        [0.8292, 0.2432, 0.4387, 0.3062, 0.6247]])
tensor([0.2650, 0.7487])


In [56]:
# More advanced indexing and operations
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0])
print(torch.where(x > 5, x, x + 2))
print(torch.tensor([0, 0, 1, 2, 2, 3]).unique())
print(x.ndimension()) # Rank of tensor
print(x.numel())  # Prints number of elements

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([2, 3, 4, 5, 6, 7, 6, 7, 8, 9])
tensor([0, 1, 2, 3])
1
10


## **Tensor Reshaping**

In [59]:
x = torch.arange(9)
x_3x3 = x.view(3, 3) # 1st way
print(x_3x3)
x_3x3 = x.reshape(3, 3) # 2nd way
print(x_3x3)

# Transpose
print(x_3x3.t())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [62]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(x1, x2)
print(torch.cat((x1, x2), dim=0))
print(torch.cat((x1, x2), dim=1))

tensor([[0.3800, 0.4789, 0.4777, 0.0413, 0.6067],
        [0.8260, 0.0969, 0.3316, 0.2362, 0.9230]]) tensor([[0.0435, 0.9524, 0.1285, 0.3910, 0.3063],
        [0.8493, 0.7704, 0.1149, 0.3772, 0.0865]])
tensor([[0.3800, 0.4789, 0.4777, 0.0413, 0.6067],
        [0.8260, 0.0969, 0.3316, 0.2362, 0.9230],
        [0.0435, 0.9524, 0.1285, 0.3910, 0.3063],
        [0.8493, 0.7704, 0.1149, 0.3772, 0.0865]])
tensor([[0.3800, 0.4789, 0.4777, 0.0413, 0.6067, 0.0435, 0.9524, 0.1285, 0.3910,
         0.3063],
        [0.8260, 0.0969, 0.3316, 0.2362, 0.9230, 0.8493, 0.7704, 0.1149, 0.3772,
         0.0865]])


In [65]:
x1.view(-1) # Flattens the tensor

tensor([0.3800, 0.4789, 0.4777, 0.0413, 0.6067, 0.8260, 0.0969, 0.3316, 0.2362,
        0.9230])

In [68]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(x.shape, z.shape)

torch.Size([64, 2, 5]) torch.Size([64, 10])


In [70]:
z = x.permute(0, 2, 1) ## interchanging dimensions